// All user-facing text of the review desk. Kurmancî is the default; English is available from the header.
// Edit freely: the keys must stay, the values are yours. Status codes (approved, needs_linguist, ...) are
// project identifiers and are shown as-is under the buttons.
window.REVIEW_DESK_LANG = {
  ku: {
    title: 'Nirxandina Peyvên Kurmancî',
    queue: 'Lîste', reviewer: 'Nirxîner', mine: 'Peyvên te', mineNone: 'hêj tune',
    mineText: '{from}–{to} · {done} ji {n} qediyan',
    showDetails: 'Hûrgiliyan nîşan bide', simpleView: 'Dîmena sade', export: 'Biryaran dakêşe', signOut: 'Derkeve', lang: 'English',
    configMissing: 'Ev kopiya malperê hêj bi databasê ve nehatiye girêdan. Di config.js de URL û kilîta projeya Supabase binivîse.',
    loginTitle: 'Têkeve', loginText: 'Têketin tenê bi vexwendinê ye. Wê e-nameya ku vexwendin jê re hat bi kar bîne.',
    email: 'E-name', password: 'Şîfre', forgot: 'Şîfre ji bîr kir?', signIn: 'Têkeve', typeEmailFirst: 'Pêşî e-nameya xwe binivîse.',
    resetSent: 'Eger ev e-name vexwendî be, girêdaneke nûkirinê hat şandin.',
    welcomeTitle: 'Bi xêr hatî', welcomeText: 'Navê nirxînerê xwe hilbijêre. Ev nav li ser her biryara te tê tomarkirin. Tenê tîpên biçûk, hejmar û xêzik (-); paşê nayê guhertin.',
    handle: 'Navê nirxîner', handlePlaceholder: 'mînak: ferhatguneri', setPassword: 'Şîfreyekê diyar bike (herî kêm 8 tîp)', start: 'Dest bi nirxandinê bike',
    handleInvalid: 'Nav: tîpên biçûk, hejmar, xêzik; 2–40 tîp.', passwordShort: 'Şîfre divê herî kêm 8 tîp be.', handleTaken: 'Ev nav hatiye girtin. Yekî din hilbijêre.',
    newPasswordTitle: 'Şîfreya nû', newPassword: 'Şîfre (herî kêm 8 tîp)', savePassword: 'Şîfreyê tomar bike',
    progress: 'Pêşketin', blocks: 'Komên 50 peyvan', nextOpenBlock: 'koma vala ya pêş', done: 'qediya', open: 'vala',
    rank: 'rêz', of: 'ji', undecided: 'Bê biryar', by: 'ji aliyê', correctedTo: 'rastkirî wekî',
    factPos: 'Cureyê peyvê (ji çavkaniyê, nehatiye kontrolkirin)', factMorph: 'Morfolojiya Hunspell', factDocs: 'Gotarên Wîkîpediyayê ku peyv tê de ye', occurrences: 'car',
    factLine: 'Rêza çavkaniya Hunspell', flags: 'nîşan', factAudit: 'Nîşaneyên kontrolê', factCap: 'Di çavkaniyê de bi tîpa mezin', capHint: 'Dibe ku navdêra taybet be',
    hint: '<b>Pejirandî</b> tê wê wateyê ku peyv <em>û</em> cureyê peyvê yê li jor herdu rast in. Eger peyv rast be lê nivîsandin an cureyê peyvê şaş be û tu ya rast dizanî, <b>Pejirandî, metadata rastkirî</b> bi kar bîne. Eger ne bawer bî, <b>Zimannas pêwîst e</b> bi kar bîne.',
    status: {
      approved:     {label:'Pejirandî',                    desc:'Peyveke rast a Kurmancî ye; nivîsandin û cureyê peyvê rast in'},
      metadata:     {label:'Pejirandî, metadata rastkirî', desc:'Peyv rast e, lê nivîsandin an cureyê peyvê divê were rastkirin'},
      rejected:     {label:'Redkirî',                      desc:'Nekeve pakêta standard; sedem pêwîst e'},
      experimental: {label:'Tenê ceribandinî',             desc:'Tenê di daneyên ceribandinê de bimîne, ne di pakêta nirxandî de'},
      linguist:     {label:'Zimannas pêwîst e',            desc:'Nediyariya zimanî heye; divê pispor biryar bide'},
      source:       {label:'Lêkolîna çavkaniyê pêwîst e',  desc:'Divê pêşî çavkanî an belgekirin were kontrolkirin'},
    },
    reasons: {
      rejected:['Peyva biyanî','Navê taybet ê biyanî','Navê cihekî biyanî','Şaşnivîsîn / forma nestandard','Tenê parçe, pêvek an klîtîk','Kurtenav an kod','Forma kêşandî, ne lema'],
      linguist:['Peyv rast e, cureyê peyvê şaş e','Devokî; forma standard ne diyar e','Nivîsandin ne diyar e','Ne bawer im ku peyv e'],
      experimental:['Argo an devkî','Kêm an teknîkî'],
      source:['Li derveyî vê çavkaniyê nayê dîtin','Dişibe xeletiyeke împortê'],
    },
    pos: {noun_fem:'navdêr, mê',noun_masc:'navdêr, nêr',noun_fem_masc:'navdêr, mê/nêr',noun:'navdêr',adjective:'rengdêr',adverb:'hoker',verb:'lêker',propn:'navdêra taybet',num:'hejmar',numeral:'hejmar',sconj:'gihanek',adp:'daçek',pronoun:'cînav',intj:'baneşan',adj_adv:'rengdêr / hoker',punctuation:'xalbendî',unknown:'nenas'},
    metaDisplay: 'Nivîsandina rast', metaPos: 'Cureyê peyvê yê rast', metaSave: 'Metadataya rastkirî tomar bike', cancel: 'Betal bike',
    metaEmpty: 'Nivîsandin nikare vala be.', metaChars: 'Tenê tîp, apostrof, xêzik û valahî destûr in.', metaSame: 'Tiştek nehat guhertin. Pejirandî bi kar bîne, an nivîsandin an cureyê peyvê rast bike.',
    notePlaceholder: 'Not (ji bo Redkirinê pêwîst e; wekî din bijare). Ji bo notê N bitikîne.', saveNote: 'Notê tomar bike', clear: 'Paqij bike', clearTitle: 'Biryarê rake (Backspace)',
    askWhy: 'Çima "{word}" tê redkirin? Yekê hilbijêre:',
    prev: '← Paşve', next: 'Pêşve →', nextOpen: 'Ya bê biryar a pêş ↵', claim: 'Vê komê bigire', release: 'Vê komê berde', claimedBy: 'Girtî: {who}',
    undo: '↶ Vegerîne: "{word}" wekî {label} hatibû nîşankirin', undone: 'Vegeriya · "{word}" niha {state} e.',
    noteSaved: 'Not hat tomarkirin.', cleared: 'Biryar hat paqijkirin.', couldNotSave: 'Nehat tomarkirin: ', couldNotClear: 'Nehat paqijkirin: ', couldNotUndo: 'Nehat vegerandin: ',
    allDone: 'Ji bo hemû peyvên vê lîsteyê biryar hatiye dayîn.', rangeDone: 'Hemû peyvên koma te qediyan. Ji bo koma pêş Enter bitikîne.',
    pickStatusFirst: 'Pêşî rewşekê hilbijêre; not bi wê re tê tomarkirin.', blockTaken: 'Ev kom ji aliyê {who} ve hatiye girtin. Jê bipirse, an komeke din hilbijêre.',
    noOpenBlock: 'Komeke vala ya bi peyvên bê biryar nemaye.', claimFailed: 'Kom nehat guhertin: ', nothingToExport: 'Hêj tiştek ji bo dakêşanê nîne.', exported: '{n} biryar hatin dakêşan.',
    loadFailed: 'Biryar nehatin barkirin: ', needsMigration: 'Ji bo rewşa 2 divê carekê supabase/migrations/002-metadata-change.sql di databasê de were xebitandin.',
    thWord: 'Peyv', thPos: 'Cureyê peyvê', thDocs: 'Gotar', thDecision: 'Biryar', thBy: 'Kî',
    block: 'Kom', ranks: 'rêz', claimedShort: 'girtî: {who}', unclaimed: 'vala',
    overrideTitle: 'Biryara nirxînerekî din biguherînî?', overrideText: '{who} di {date} de ev peyv wekî "{label}" nîşan kiribû. Biryara wî/wê di dîrokê de dimîne.', keepTheirs: 'Ya wan bihêle', replaceMine: 'Bi ya min biguherîne',
    guideSummary: 'Çawa biryar bidim, bişkokên klavyeyê û wateya her rewşê',
    guideIntro: 'Tu sînorê baweriyê yî. Li vir tu tişt ji aliyê nivîsbariyê ve nayê pejirandin; her rewşa ku tu hilbijêrî dibe biryareke mirovî û bi navê te tê tomarkirin. Hejmar nîşan didin ka peyv di çend gotarên Wîkîpediya Kurmancî de derbas dibe. Ew dibêjin pêşî li çi binêre, ne ku peyv rast e an na.',
    guide: {
      approved: 'Peyva împortkirî û metadataya wê wekî xwe ji bo pakêta nirxandî tên pejirandin.',
      metadata: 'Peyv rast e lê nivîsandin an cureyê peyvê divê were guhertin. Tenê dema tu ya rast dizanî bi kar bîne.',
      rejected: 'Nabe ku bikeve pakêta standard. Peyva biyanî, navê taybet ê biyanî, şaşnivîsîn, parçe. Sedem pêwîst e.',
      experimental: 'Dikare di daneyên ceribandinê de bimîne lê ne di pakêta nirxandî de.',
      linguist: 'Nediyariya zimanî heye; divê pispor biryar bide.',
      source: 'Pêşî belgekirin an çavkaniyeke bihêztir pêwîst e.',
    },
    guideKeys: 'Bişkok: <b>1–6</b> biryar, <b>Backspace</b> paqij bike, <b>←/→</b> bimeşe, <b>Enter</b> ya bê biryar a pêş, <b>N</b> not. Di dîmena sade de malper komeke 50 peyvan ji bo te vediqetîne û gava tu biqedînî derbasî koma pêş dibe; di dîmena hûrgilî de tu komên xwe bi xwe digirî.',
  },
  en: {
    title: 'Kurmancî Review Desk',
    queue: 'Queue', reviewer: 'Reviewer', mine: 'Your words', mineNone: 'none yet',
    mineText: '{from}–{to} · {done} of {n} done',
    showDetails: 'Show details', simpleView: 'Simple view', export: 'Export decisions', signOut: 'Sign out', lang: 'Kurmancî',
    configMissing: 'This copy of the site has no database configured yet. Edit config.js with your Supabase project URL and key.',
    loginTitle: 'Sign in', loginText: 'Access is by invitation. Use the email address that received your invitation.',
    email: 'Email', password: 'Password', forgot: 'Forgot password', signIn: 'Sign in', typeEmailFirst: 'Type your email first.',
    resetSent: 'If that address is invited, a reset link is on its way.',
    welcomeTitle: 'Welcome', welcomeText: 'Choose the reviewer handle the project will record on every decision you make. Lowercase letters, digits, and hyphens; it cannot be changed later.',
    handle: 'Reviewer handle', handlePlaceholder: 'e.g. ferhatguneri', setPassword: 'Set a password (8+ characters)', start: 'Start reviewing',
    handleInvalid: 'Handle: lowercase letters, digits, hyphens, 2–40 characters.', passwordShort: 'Password needs at least 8 characters.', handleTaken: 'That handle is taken. Choose another.',
    newPasswordTitle: 'New password', newPassword: 'Password (8+ characters)', savePassword: 'Save password',
    progress: 'Progress', blocks: 'Blocks of 50', nextOpenBlock: 'next unclaimed', done: 'done', open: 'open',
    rank: 'rank', of: 'of', undecided: 'Undecided', by: 'by', correctedTo: 'corrected to',
    factPos: 'Part of speech (imported, unverified)', factMorph: 'Hunspell morphology', factDocs: 'Wikipedia articles containing it', occurrences: 'occurrences',
    factLine: 'Hunspell source line', flags: 'flags', factAudit: 'Audit flags', factCap: 'Capitalized in source', capHint: 'Possibly a proper noun',
    hint: '<b>Approved</b> means the word <em>and</em> the imported part of speech shown above are both right. If the word is right but the spelling or part of speech is wrong and you know the correct one, use <b>Approved, metadata corrected</b>. If you are not certain, use <b>Needs linguist</b>.',
    status: {
      approved:     {label:'Approved',                    desc:'Valid Kurmancî word; spelling and part of speech are right'},
      metadata:     {label:'Approved, metadata corrected',desc:'Valid word, but the spelling or part of speech must be corrected'},
      rejected:     {label:'Rejected',                    desc:'Keep out of the default pack; reason required'},
      experimental: {label:'Experimental only',           desc:'Keep in experimental data, not in the reviewed pack'},
      linguist:     {label:'Needs linguist',              desc:'Unresolved linguistic uncertainty; a specialist must decide'},
      source:       {label:'Needs source investigation',  desc:'Provenance or attestation must be checked first'},
    },
    reasons: {
      rejected:['Foreign word','Foreign proper name','Foreign place name','Misspelling / non-standard form','Fragment, affix, or clitic only','Abbreviation or code','Inflected form, not a lemma'],
      linguist:['Word valid, part of speech wrong','Dialectal; standard form unclear','Spelling uncertain','Unsure if it is a word'],
      experimental:['Slang or colloquial','Rare or technical'],
      source:['Cannot find outside this source','Looks like an import artifact'],
    },
    pos: {noun_fem:'noun, feminine',noun_masc:'noun, masculine',noun_fem_masc:'noun, fem./masc.',noun:'noun',adjective:'adjective',adverb:'adverb',verb:'verb',propn:'proper noun',num:'numeral',numeral:'numeral',sconj:'conjunction',adp:'preposition / adposition',pronoun:'pronoun',intj:'interjection',adj_adv:'adjective / adverb',punctuation:'punctuation',unknown:'unknown'},
    metaDisplay: 'Corrected spelling', metaPos: 'Corrected part of speech', metaSave: 'Save corrected metadata', cancel: 'Cancel',
    metaEmpty: 'Spelling cannot be empty.', metaChars: 'Only letters, apostrophes, hyphens and spaces are allowed.', metaSame: 'Nothing changed. Use Approved instead, or correct the spelling or part of speech.',
    notePlaceholder: 'Note (required for Reject; optional otherwise). Press N to focus.', saveNote: 'Save note', clear: 'Clear', clearTitle: 'Remove decision (Backspace)',
    askWhy: 'Why reject "{word}"? Pick one:',
    prev: '← Prev', next: 'Next →', nextOpen: 'Next undecided ↵', claim: 'Claim this block', release: 'Release this block', claimedBy: 'Claimed by {who}',
    undo: '↶ Undo: "{word}" was marked {label}', undone: 'Undone · "{word}" is {state} again.',
    noteSaved: 'Note saved.', cleared: 'Decision cleared.', couldNotSave: 'Could not save: ', couldNotClear: 'Could not clear: ', couldNotUndo: 'Could not undo: ',
    allDone: 'Every word in this queue has a decision.', rangeDone: 'All words in your range are done. Press Enter for the next range.',
    pickStatusFirst: 'Pick a status first; the note is saved with it.', blockTaken: 'Block is claimed by {who}. Ask them, or pick another block.',
    noOpenBlock: 'No unclaimed block with open words.', claimFailed: 'Could not update claim: ', nothingToExport: 'Nothing to export yet.', exported: 'Exported {n} decisions.',
    loadFailed: 'Could not load decisions: ', needsMigration: 'Status 2 needs the database migration supabase/migrations/002-metadata-change.sql to be run once.',
    thWord: 'Word', thPos: 'Part of speech', thDocs: 'Articles', thDecision: 'Decision', thBy: 'By',
    block: 'Block', ranks: 'ranks', claimedShort: 'claimed by {who}', unclaimed: 'unclaimed',
    overrideTitle: "Change another reviewer's decision?", overrideText: '{who} marked this "{label}" on {date}. Their decision stays in the history table.', keepTheirs: 'Keep theirs', replaceMine: 'Replace with mine',
    guideSummary: 'How to decide, keyboard keys, and what each status means',
    guideIntro: 'You are the trust boundary. Nothing here is approved by software; every status you pick becomes a human decision recorded under your reviewer handle. Counts show how many Kurmancî Wikipedia articles contain the word. They tell you what to look at first, not whether the word is correct.',
    guide: {
      approved: 'The imported entry and its metadata are accepted as-is for the reviewed pack.',
      metadata: 'The word is valid but the spelling or part of speech must be replaced. Use it only when you know the correct replacement.',
      rejected: 'Must not enter the default pack. Foreign word, foreign proper name, misspelling, fragment. A reason is required.',
      experimental: 'May stay in experimental data but not in the reviewed pack.',
      linguist: 'Unresolved linguistic uncertainty; a specialist must decide.',
      source: 'The candidate needs stronger attestation or provenance before a decision.',
    },
    guideKeys: 'Keys: <b>1–6</b> decide, <b>Backspace</b> clear, <b>←/→</b> move, <b>Enter</b> next undecided, <b>N</b> note. In the simple view the site reserves a range of 50 words for you and moves to the next range when you finish; in the detailed view you claim blocks yourself.',
  },
};
